### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by chinaray** [ChrisLeeGit/serial-assistant#2]
接收区数据多了以后，直接点X关闭，会导致串口这个页面死掉；点击"查找“旁边的”关闭“也会死掉

**Comment by ChrisLeeGit** [comment]
嗯嗯，如果可以的话 希望你能帮忙修复 :)

**Comment by chinaray** [comment]
if (showReceiveData)
{
	//chinaray
	string text = (new System.Windows.Documents.TextRange
		(recvDataRichTextBox.Document.ContentStart, recvDataRichTextBox.Document.ContentEnd)).Text;
	if (text.Length > 4096)
	{
		recvDataRichTextBox.Document.Blocks.Clear();
	}

	// 根据显示模式显示接收到的字节.
	recvDataRichTextBox.AppendText(Utilities.BytesToText(recvBuffer, receiveMode, serialPort.Encoding));
	recvDataRichTextBox.ScrollToEnd();
}

**Comment by ChrisLeeGit** [comment]
不在 win 下做开发了，所以也没法测试，如果你修复了并且没问题的话，可以发一个 PR，多谢。
